version: '3'
services:
  top.api:
    image: docker.pkg.github.com/andrewvolosevich/nest-learning-server/top-api-demo:develop
    container_name: top-api
    restart: always
    ports:
      - 3003:3003
    volumes:
      - ./.env:/opt/app/.env