#
#name: Publish Docker
#on:
#  push:
#    branches: [master]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Publish to Registry
#        uses: elgohr/Publish-Docker-Github-Action@v5
#        with:
#          registry: https://ghcr.io
#          name: https://ghcr.io/AndrewVolosevich/nest-learning-server/top-api
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          tags: "develop"
#name: Publish Docker
#
#on:
#  push:
#    branches: [master]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Publish to registry
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          registry: docker.pkg.github.com
#          name: docker.pkg.github.com/AndrewVolosevich/nest-learning-server/top-api
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          tags: "develop"

#name: Docker Publish
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  publish:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Build and publish Docker image
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        run: |
#          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin https://ghcr.io
#          docker build -t https://ghcr.io/andrewvolosevich/nest-learning-server/top-api:latest .
#          docker push https://ghcr.io/andrewvolosevich/nest-learning-server/top-api:latest

name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: platonchik/top-api

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}